### ISSUE TITLE
`php artisan facade:diag` Command doesn't work.

### ISSUE THREAD

**Issue by rizalio** [nauvalazhar/facade-please#1]
I've installing your package through composer, & the package is worked. but, while I'm trying to run `php artisan facade:diag` command, the command doesn't run properly, insted of throw an axception.

```
                                                           
  [ReflectionException]                                    
  Class App/Marketplace/UsermanClassFacade does not exist  
                                                           
```

Why this thing happen?

![screenshot from 2017-09-04 17-48-07](https://user-images.githubusercontent.com/22221916/30023372-3c6e5c3a-9199-11e7-8ea2-e89741e87ff0.png)

**Comment by nauvalazhar** [comment]
Fixed! https://github.com/nauvalazhar/facade-please/pull/2
